plugins {
    id 'java-library'
    id 'jacoco'
    id 'maven-publish'
    id 'printscript.java-common-conventions'
}

group = 'ar.edu.austral.ingsis.printscript'
version = '1.0.0'

jacoco {
    toolVersion = '0.8.11'
}

tasks.withType(Test).configureEach {
    finalizedBy(tasks.named('jacocoTestReport'))
}

tasks.named('jacocoTestReport') {
    dependsOn(tasks.named('test'))
    reports {
        xml.required.set(true)
        html.required.set(true)
        csv.required.set(false)
    }
}

tasks.named('jacocoTestCoverageVerification') {
    dependsOn(tasks.named('test'))
    violationRules {
        rule {
            limit { minimum = 0.80 }
        }
    }
}

tasks.named('check') {
    dependsOn(tasks.named('jacocoTestCoverageVerification'))
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = "printscript-${project.name}"
        }
    }
    repositories {
        maven {
            name = 'GitHubPackages'
            url = uri('https://maven.pkg.github.com/ing-sis-grupo10/printscript')
            credentials {
                username = System.getenv('GITHUB_ACTOR')
                password = System.getenv('GITHUB_TOKEN')
            }
        }
    }
}
