plugins {
    id 'printscript.java-library-conventions'
}

dependencies {
    implementation project(':ast')
    implementation project(':common')
    implementation 'com.google.code.gson:gson:2.10.1'

    testImplementation project(':lexer')
    testImplementation project(':parser')
    testImplementation project(':semantic')
}
